---
- name: Update and upgrade all packages on all hosts
  hosts: all
  become: false  # Ensure we are not trying to use sudo

  tasks:
    - name: Update and upgrade apt packages
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Update and upgrade yum packages
      when: ansible_pkg_mgr == 'yum'
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Update and upgrade dnf packages
      when: ansible_pkg_mgr == 'dnf'
      ansible.builtin.dnf:
        name: '*'
        state: latest

    - name: Update and upgrade zypper packages
      when: ansible_pkg_mgr == 'zypper'
      ansible.builtin.zypper:
        name: '*'
        state: latest

    - name: Update and upgrade apk packages (Alpine Linux)
      when: ansible_pkg_mgr == 'apk'
      ansible.builtin.command:
        cmd: apk upgrade --no-cache
